/* Generated by updaterev.sh, do not edit */
#ifdef SDL_VENDOR_INFO
#define SDL_REVISION "SDL-release-2.24.0-669-g64c93f780 (" SDL_VENDOR_INFO ")"
#else
#define SDL_REVISION "SDL-release-2.24.0-669-g64c93f780"
#endif
#define SDL_REVISION_NUMBER 0
